"""Generate deterministic, secret-free firmware build assets."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import tempfile


@dataclass(frozen=True)
class BuildAssetsResult:
    header_path: Path


def _public_defaults() -> dict:
    """Return conservative defaults suitable for every supported target."""

    return {
        "audit": {
            "enabled": True,
            "logging": {
                "log_config_changes": True,
                "log_denied": True,
                "log_ratelimits": True,
                "log_security_events": True,
                "log_system_events": True,
                "log_timeouts": True,
            },
            "rate_limiting": {"max_events_per_second": 100},
        },
        "debug": {"color": True, "level": 2},
        "ids": {
            "general": {
                "enabled": True,
                "max_per_sec_enip": 100,
                "max_per_sec_modbus": 100,
                "max_per_sec_opcua": 100,
                "max_per_sec_pn": 100,
                "max_per_sec_s7": 100,
                "replay_window_ms": 5000,
            }
        },
        "network": {
            "ethernet": {
                "dhcp": True,
                "enabled": True,
                "gateway": "",
                "ip": "",
                "netmask": "",
                "promiscuous": True,
            },
            "wifi": {
                "connect_timeout_sec": 20,
                "dhcp": True,
                "dns": "",
                "enabled": False,
                "gateway": "",
                "http_time_sync": "",
                "ip": "",
                "netmask": "",
                "ntp": "pool.ntp.org",
                "password": "",
                "scan_on_fail": False,
                "ssid": "",
                "time_sync": "ntp",
            },
        },
        "plugins": {
            "ethernetip": {"enabled": True},
            "modbus": {"enabled": True},
            "opcua": {"enabled": True},
            "profinet": {"enabled": True},
            "s7": {"enabled": True},
        },
        "reporting": {
            "email": {"configuration": {}, "enabled": False},
            "file": {"configuration": {}, "enabled": True},
            "gpio": {"configuration": {}, "enabled": False},
            "mqtt": {"configuration": {}, "enabled": False},
            "serial": {"configuration": {}, "enabled": True},
            "webhook": {"configuration": {}, "enabled": False},
        },
        "scanner": {
            "default_timeout_ms": 2000,
            "enabled": False,
            "jobs": [],
            "max_parallel": 1,
            "rate_limit_per_min": 30,
            "scheduling": {"enabled": False},
        },
        "security": {
            "alert_policy": {
                "email": {
                    "enabled": False,
                    "recipients": [],
                    "subject": "ICS security alert",
                    "throttle_minutes": 5,
                },
                "gpio": {
                    "buzzer_pin": -1,
                    "critical_pin": -1,
                    "enabled": False,
                    "warning_pin": -1,
                },
                "webhook": {"enabled": False, "token": "", "url": ""},
            },
            "certificate_validation": True,
            "flash_encryption": False,
            "opcua_enforce_security": True,
            "policy": {"block_s7_plc_stop": True},
            "secure_boot": False,
        },
        "watchdog": {
            "enabled": True,
            "monitor_idle_cores": False,
            "panic_on_timeout": False,
            "timeout_seconds": 30,
        },
    }


def _header_bytes() -> bytes:
    config = json.dumps(
        _public_defaults(), ensure_ascii=True, separators=(",", ":"), sort_keys=True
    )
    header = (
        "// Generated by scripts/build_assets.py. Do not edit.\n"
        "#pragma once\n\n"
        "namespace esp32_ot_build {\n"
        "static constexpr char kEmbeddedPublicConfigJson[] = "
        f'R"ESP32CFG({config})ESP32CFG";\n'
        "}  // namespace esp32_ot_build\n"
    )
    return header.encode("utf-8")


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_bytes() == content:
        return
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        temporary = Path(handle.name)
        handle.write(content)
    temporary.replace(path)


def generate_build_assets(
    project_dir: Path | str, build_dir: Path | str, board: str | None = None
) -> BuildAssetsResult:
    """Generate public assets; ``board`` is accepted for a stable build interface."""

    Path(project_dir).resolve(strict=True)
    Path(build_dir).resolve().mkdir(parents=True, exist_ok=True)
    if board is not None and not isinstance(board, str):
        raise TypeError("board must be a string or None")
    header_path = Path(build_dir).resolve() / "generated" / "esp32_ot_build_assets.h"
    legacy_header = header_path.parent / "esp32_ot_generated_credentials.h"
    if legacy_header.exists():
        legacy_header.unlink()
    _atomic_write(header_path, _header_bytes())
    return BuildAssetsResult(header_path=header_path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-dir", type=Path, required=True)
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--board", default="")
    args = parser.parse_args()
    result = generate_build_assets(args.project_dir, args.build_dir, args.board)
    print(f"Public build assets ready: {result.header_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
