[platformio]
src_dir = main
build_dir = ${sysenv.USERPROFILE}/.platformio/build/ESP32-OT-Security-Assessment-coprocessor

[env:esp32c6-coprocessor]
platform = https://github.com/pioarduino/platform-espressif32.git#4cf6992078a95fb9ab8352fe7811f4eec0d359af
board = esp32-c6-devkitc-1
framework = espidf

board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = partitions.csv
board_build.sdkconfig_defaults = sdkconfig.defaults

upload_speed = 921600
monitor_speed = 115200
